### ISSUE TITLE
Too many changes without any difference

### ISSUE THREAD

**Issue by nisiode** [iobroker-community-adapters/ioBroker.discovergy#75]
https://github.com/iobroker-community-adapters/ioBroker.discovergy/blob/21a4f4f33cd653e271a158f095f3358ed4c1dd83/main.js#L139

**Describe the bug**  
As developer of ioBroker.iogo, I see huge amount of object changes being logged without any changes.

**Expected behavior**  
Change objects only if there are real changes being made to the existing object.

**Comment by DutchmanNL** [comment]
Agree I will change that to an initialization Routine only thank you !

**Comment by nisiode** [comment]
thank you for reducing my billing

**Comment by DutchmanNL** [comment]
i realized if you combine this with SourceAnalytix your ioBroker gets into an complete loop so fix is on its way :)

**Comment by DutchmanNL** [comment]
should be fixed in 0.5.1

https://github.com/iobroker-community-adapters/ioBroker.discovergy/commit/d28f06c33ba81e0985895b188153950c706817b0#diff-7a9076d6d94e62c13d641aa71f19ae8eR237-R273

I compare now every object type before executing a setstate, so at initialization you always have a setObject ( which make sense ) but later during runtime only if attributes are not equal to value stored in memory
